site_name: PlayFab SDK
site_description: 'A complete PlayFab SDK for Roblox'
site_author: 'Brooke Rhodes'
docs_dir: docs/
repo_name: 'grilme99/RobloxPlayFabSDK'
repo_url: 'https://github.com/grilme99/RobloxPlayFabSDK'
nav:
    - Home: index.md
theme:
  name: 'material'