name: CI
on:
  push:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit Testing
    runs-on: windows-latest
    steps:
      # checkout + npm install
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: bahmutov/npm-install@v1.1.0

      # install roblox-ts dev
      - run: |
          pushd ..
          git clone -b refactor https://github.com/roblox-ts/roblox-ts.git
          pushd roblox-ts
          npm ci
          npm run build
          npm run devlink
          popd
          popd
      # install Roblox Studio
      - run: pip install wget psutil
      - run: python tests/scripts/install.py "${{ secrets.ROBLOSECURITY }}"
      # install rojo + run-in-roblox
      - uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: foreman install

      # compile and run tests
      - run: npm test